disabled_rules:
  - statement_position
  - trailing_whitespace
  - trailing_newline
  - file_length
  - line_length
  - type_body_length
  - function_parameter_count
  - function_body_length
  - opening_brace
  - variable_name
  - cyclomatic_complexity

excluded:
  - ScotTrafficTests
  - ScotTrafficUITests
  - Libraries
  - Submodules

